port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - name: us
    server: vpn.88cloud.asia
    port: 443
    type: trojan
    password: 3cf50a8f-35b9-46a5-9a86-9cdbcd6ee3a6
    network: ws
    tls: true
    udp: true
    sni: vpn.88cloud.asia
    ws-opts:
      path: "/3cf50a8f-35b9-46a5-9a86-9cdbcd6ee3a6"
      headers:
        Host: vpn.88cloud.asia
      max-early-data: 4096
      early-data-header-name: Sec-WebSocket-Protocol
      
  - name: worker
    server: speed.marisalnc.com
    port: 443
    type: trojan
    password: jVjyLiiW9Bki887I
    network: ws
    tls: true
    udp: true
    sni: cdn.88cloud.asia
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: cdn.88cloud.asia
      max-early-data: 4096
      early-data-header-name: Sec-WebSocket-Protocol

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - DIRECT
      - us
      - worker
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - us
      - worker
  - name: 海外流量
    type: select
    proxies:
      - 节点选择
      - 自动选择
      - 全球直连
      - us
      - worker
  - name: 代理信息
    type: select
    proxies:
      - 节点选择
      - 全球直连
      - us
      - worker
  - name: 视频服务
    type: select
    proxies:
      - 全球直连
      - 节点选择
      - us
      - worker
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 全球直连
      - us
      - worker
  - name: 推送FCM
    type: select
    proxies:
      - 节点选择
      - 全球直连
      - 自动选择
      - us
      - worker
  - name: 全球直连
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 自动选择
  - name: 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 应用例外
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 浏览器加速
    type: select
    proxies:
      - 节点选择
      - 全球直连
      - 自动选择
      - us
      - worker
rules:
  - DOMAIN-SUFFIX,acl4.ssr,全球直连
  - DOMAIN-SUFFIX,ip6-localhost,全球直连
  - DOMAIN-SUFFIX,ip6-loopback,全球直连
  - DOMAIN-SUFFIX,lan,全球直连
  - DOMAIN-SUFFIX,local,全球直连
  - DOMAIN-SUFFIX,localhost,全球直连
  # 过滤服务器IP
